version: 2.1
orbs:
  node: circleci/node@4.1
jobs:
  run_tests:
    docker:
      - image: cimg/node:15.1
      - image: circleci/postgres:9.5-postgis
        environment:
          POSTGRES_USER: $PGUSER
          POSTGRES_DB: $PGDATABASE
          POSTGRES_PASSWORD: $PGPASSWORD
          POSTGRES_HOST: $PGHOST
          POSTGRES_PORT: $PGPORT
    steps:
      - checkout #alias for git clone\
      - node/install-packages
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run unit tests
          command: |
            npm run test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  build_test:
    jobs:
      - run_tests