DROP TABLE IF EXISTS chatlist;
DROP TABLE IF EXISTS conversation;

CREATE TABLE chatlist(
  chatId INT PRIMARY KEY NOT NULL,
  uid1 INT NOT NULL,
  uid2 INT NOT NULL,
  unread INT,
  time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE conversation(
  chatId INT PRIMARY NOT NULL,
  messageId INT NOT NULL,
  senderId INT NOT NULL,
  body VARCHAR,
  photoUrl VARCHAR,
  read BOOLEAN,
  time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);